---
deployment:
  tasks:
    - export DEPLOYPATH=/home/infojawatimur/kajiindonesia.com_new/
    - /bin/cp -R $CPCWD/* $DEPLOYPATH
    - /bin/cp -R $CPCWD/.* $DEPLOYPATH
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:cache